[[pages]]
path = "../dashboard.py"
name = "Stock Price Predictions"

[[pages]]
path = "../pages/performance.py"
name = "Model Comparison"

[[pages]]
path = "../pages/backtests.py"
name = "Backtests"

[[pages]]
path = "..//pages/trades.py"
name = "Trades"
