[[pages]]
path = "dashboard.py"
name = "Stock Price Predictions"

[[pages]]
path = "pages/trades.py"
name = "Trading Performance"

[[pages]]
path = "pages/models.py"
name = "Model Comparison"

[[pages]]
path = "pages/backtests.py"
name = "Backtests"
