[[pages]]
path = "dashboard.py"
name = "Stock Price Predictions"

[[pages]]
path = "pages/performance.py"
name = "Model Performance"

[[pages]]
path = "pages/trades.py"
name = "Trading Performance"

[[pages]]
path = "pages/backtests.py"
name = "Backtests"
